Implement ipAllowList
digitalbazaar/bedrock-kms-http pull request #47
Opened 2021-03-09 18:34 UTC by mattcollier

@dlongley there are a couple/few fixmes to be resolved immediately here.

### Added
- Keystore configurations may now include an optional `ipAllowList` array. If
  specified, the KMS system will only execute requests originating from IPs
  listed in `ipAllowList`. This applies to key operations for all keys in the
  keystore as well as modification of the configuration itself.

2021-03-09 18:55 UTC, dlongley commented on lib/http.js
> +    // server config.server.host or domain?
Yes, this should be the host value for the KMS server itself (it is no longer for some application that is using the KMS system).

2021-03-09 18:55 UTC, dlongley commented on lib/http.js
> +        verified = true;
We should just return here -- no need to keep iterating through the `ipAllowList`.

2021-03-09 18:55 UTC, dlongley commented on lib/http.js
> +  // !!! I believe we want to remove this host check entirely, is that correct?
If this is now handled by `expectedHost` and http-signature-zcap-verify, yes.

2021-03-09 22:37 UTC, dlongley requested changes
We don't check the `ipAllowList` on the get configs call here or in the revocations endpoint. We should add it.

For the get configs call we can just omit the configs that cannot be obtained from the source IP vs. throwing if any one of them can't be obtained.

2021-03-11 22:38 UTC, mattcollier commented
> We don't check the `ipAllowList` on the get configs call here or in the revocations endpoint. We should add it.
> 
> For the get configs call we can just omit the configs that cannot be obtained from the source IP vs. throwing if any one of them can't be obtained.

@dlongley Done, along with some test for keystores `get`, `find` and the create revocations endpoint.

There's more work to be done wrt getting zcaps fully implemented before another release, but I'd like to get this PR merged down.

2021-03-11 23:16 UTC, dlongley approved these changes
Thanks!

2021-03-12 14:46 UTC, merged